[package]
name = "odoo-rust-sfu"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
serde = "1.0.214"
log = "0.4.22"
env_logger = "0.11.5"
jsonwebtoken = "9.3.0"
uuid = { version = "1.11.0", features = ["v4"] }
tokio = { version = "1.41.0", features = ["full"] }
once_cell = "1.20.2"
# mediasoup = "0.17.1"
