max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
wrap_comments = true
imports_granularity = "Crate"

unstable_features = true
group_imports = "StdExternalCrate" # needs nightly toolchain and unstable, hopefully stable at some point...
